### ISSUE TITLE
[BUG] app.terraswap.io on a non googleplay service android device does not invoke the terrastation app

### ISSUE THREAD

**Issue by krauq4** [terraswap/terraswap#26]
**Describe the bug**

I have an android device without google play services, and terraswap.io webapp does not invoke the installed terrastation app on android due to the use of firebase intents
E.g:
```
11-04 14:20:24.836 1661 2134 I ActivityTaskManager: START u0 {act=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK cat=[android.intent.category.BROWSABLE] dat=https://terrastation.page.link/... flg=0x14000000 pkg=com.google.android.gms cmp=com.google.android.gms/.appinvite.AppInviteAcceptInvitationActivity (has extras)} from uid 10294
```

**To Reproduce**
Try to connect wallet on a non googleplay service android device

**Context & versions**
Happens on latest version of the webapp and terrastation app.

**(if applicable) suggested solution**
terra.cards webapp in contrast does it without using firebase, and the terrastation app gets invoked without any issues
E.g:
```
11-04 14:39:05.310 1478 3288 I ActivityTaskManager: START u10 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=terrastation://send/?payload=eyJhZGRyZXNzIjoidGVycmExeW5ld2NrMGx2Y2pudHhtNGV3OGxwaGZoNzI5cjZlY3c3NWhuZTAiLCJhbW91bnQiOiIyMDgwMDAwMDAiLCJ0b2tlbiI6InV1c2QiLCJtZW1vIjoiMTgxNzIifQ== flg=0x14000000 cmp=money.terra.station/.MainActivity (has extras)} from uid 1010254
```

So if terraswap app switches to normal intents instead of firebase, devices that dont have googleplay services can use terraswap.io webapp on such devices, which now is not possible.

I would be thankful if this gets sorted.

Thanks.

**Comment by JoowonYun** [comment]
It has nothing to do with contracts. Check out that repository. https://github.com/terraswap/terraswap-web-app
