### ISSUE TITLE
[BUG] academy.terra.money tutorial bug

### ISSUE THREAD

**Issue by ColtraneNadler** [terraswap/terraswap#27]
**Describe the bug**

Im following along on the academy.terra.money tutorial,
and when I run the code from https://github.com/larry0x/spacecamp-2021-workshop

I get the error
`
Instantiating TerraSwap Token contract... (node:47952) UnhandledPromiseRejectionWarning: Error: Transaction failed!
code: 3
codespace: wasm
raw_log: failed to execute message; message index: 0: Caught panic: instantiate wasm contract failed{"txhash":"A78A93E4AA9285006E59A395AFFFEFE04B2FD818691A2A076DF03C7E5954BD12","raw_log":"failed to execute message; message index: 0: Caught panic: instantiate wasm contract failed","gas_wanted":8000000,"gas_used":60926,"height":4759,"code":3,"codespace":"wasm"}
`

and it my LocalTerra logs it outputs
`
terrad_1         | thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
terrad_1         |   left: `-1`,
terrad_1         |  right: `0`: registering new sigaltstack failed', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-vm-2.0.0/src/trap/traphandlers.rs:984:9
`

any ideas?

**To Reproduce**
Describe the steps to reproduce the behavior.

ts-node main.ts

**Context & versions**
Delineate the correct versions of all the components involved in reproducing the bug. 

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by JoowonYun** [comment]
Even if you have txhash, I can't check your local network. It seems to be a parameter problem, and please contact us through discord.
