### ISSUE TITLE
[BUG] belief_price and max_spread not respected?

### ISSUE THREAD

**Issue by tuloski** [terraswap/terraswap#31]
I think I found a transaction where the terraswap belief_price and spread is not respected. It seems a bug.

The transaction sends 13579720 uluna for bluna with belief_price: "0.98984022497681" and max_spread: "0.0025167438940065". Based on this numbers the minimum received should be (13579720/0.98984022497681*(1-0.0025167438940065)) = 13684575, but it actually received 13652065 which is less.

Did I misinterpret what belief_price and max_spread do or there is a bug?

**Comment by tuloski** [comment]
Actually the logic here seems fine:
https://github.com/terraswap/terraswap/blob/c19b241410cc5882d7bcf96d2a6228af3629a897/contracts/terraswap_pair/src/contract.rs#L643-L658

**Comment by tuloski** [comment]
But there is something wrong since from the log I see:

offer_amount: 13579720
return_amount: 13652065
tax_amount: 0
spread_amount: 182
commission_amount: 41079

How can it be spread_amount: 182 if the expected_amount should be 13719103 and the return_amount is 13652065? The difference is 67038, not 182.

**Comment by tuloski** [comment]
I see the problem here:
https://github.com/terraswap/terraswap/blob/c19b241410cc5882d7bcf96d2a6228af3629a897/contracts/terraswap_pair/src/contract.rs#L395-L401

To the check for spread assert function it is passed as return_amount the real return_amount + the commission amount which is wrong. It shouldn't include the commission amount IMO.

**Comment by tuloski** [comment]
Let's do a simple Example.
I want to trade 1 Luna for UST. The pool price is 100.
Expected amount is 99.7 UST with 0.3 UST fee. So belief_price is 1/99.7=0.01003.
If I put max_spread=1%, I expect the transaction to succeed if I get at least 99.7*(1-0.01) = 98.703 UST, and this is also what terraswap UI is showing.
Now let's suppose that the price changes to 98.9. The fee becomes 0.2967 and the received amount is 98.6033. I expect it to fail (because the received 98.603 < 98.703 expected), but instead it succeeds, because the spread is computed as (99.7-98.9)/99.7 = 0.008024 which is still lower than 1%.
If the spread was instead computed without the fee as (99.7-98.6033)/99.7 = 0.011 which would exceed max_spread.

**Comment by JoowonYun** [comment]
Yes. In contract, current belief_price is based on the actual swap based amount including commission, and I think the actual swap based value is correct. And In the web app, the price is calculated on a per-user basis.

But, there are many people who are confused about this part, so I think it would be good to discuss it.

**Comment by tuloski** [comment]
I agree that we can discuss about the belief_price, but I think this bug persists anyway.
Transactions which shouldn't succeed might succeed and users can lose funds (it happened to me multiple times).

**Comment by tuloski** [comment]
Also consider the limit case of "max_spread = 0".
Considering the previous example:
Expected amount is 99.7 UST with 0.3 UST fee. So belief_price is 1/99.7=0.01003.
I expect the transaction to succeed only if 99.7 UST are delivered (zero spread).
Now the price changes slightly to 99.9. The amount received is 99.9*0.997 = 99.6003. The transaction should fail, but it succeeds, because the return_amount (99.9 because fees are included) > expected_return (99.7).
It's clearly a problem.
