### ISSUE TITLE
Document whether the "return_amount" factors in the commission

### ISSUE THREAD

**Issue by neelkamath** [terraswap/terraswap#32]
The [simulation response](https://docs.terraswap.io/docs/howto/freq_used_msg/#simulation--reverse-simulation) has a `return_amount` field. To get the rate, I'd divide the offer quantity by the `return_amount`. If I offer 1 Luna, ask for UST, and the `return_amount` is `100`, is the `100` inclusive of the LP commission of 0.3%?

**Comment by JoowonYun** [comment]
> The [simulation response](https://docs.terraswap.io/docs/howto/freq_used_msg/#simulation--reverse-simulation) has a `return_amount` field. To get the rate, I'd divide the offer quantity by the `return_amount`. If I offer 1 Luna, ask for UST, and the `return_amount` is `100`, is the `100` inclusive of the LP commission of 0.3%?

This value excludes 0.3% commission. https://github.com/terraswap/terraswap/blob/97cefa337798bdb0cba0327dd4152607839a5c77/contracts/terraswap_pair/src/contract.rs#L564
