### ISSUE TITLE
ROBOHERO TOKEN

### ISSUE THREAD

**Issue by mexmet23** [terraswap/terraswap#35]
3C9B08718A963A82353C17CC9D141E64A85476AFB860544AA3A0C4E3D2122D92

tx hash 11.127 ust but I have 5 usd in my account why

I swapped my robohero tokens with usdt on the terraswap channel today, no money in my wallet can you help me please

I didn't know that you can swap with upper, when it was usdt among the options, I chose it 

While swapping rope hero tokens, there was usdt in the options, I traded here for the first time. How can it suddenly drop to 5 dollars: I converted it to usdt, not to ust.

terra104dnzgzzx7hjt32sml9zspqfmvr7fdae8l6vy8

This person took action immediately after me. Please help me get my money back

If it is so risky to convert to usdt, why do you put it in the options, only put UST

**Comment by JoowonYun** [comment]
It was already explained in discord
