### ISSUE TITLE
[BUG] Can't provide initial liquidity for trading pair KLT/LUNC

### ISSUE THREAD

**Issue by lunc808** [terraswap/terraswap#70]
Hello, I want to launch my pair KLT/LUNC on terraswap classic but when I try to execute provide_liquidity message it gives me code error:3. 

Without providing LP to the pair I sent KLT and LUNC manually to the pool without receiving LP but even now I can't just add liquidity through your UI, it says pool balance is not enough.

**Comment by nowooj** [comment]
Resolved in Discord.
